// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package polymer_prover

import (
	"fmt"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
)

type InternalAccountAccount struct {
	// store the owner's public key
	Authority ag_solanago.PublicKey

	// Client type used on peptide to generate the proof. It is part of the proof key
	ClientType string

	// Known signer address that signed the peptide state root
	SignerAddr     [20]uint8
	PeptideChainId uint64
}

var InternalAccountAccountDiscriminator = [8]byte{151, 149, 233, 78, 143, 12, 17, 254}

func (obj InternalAccountAccount) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(InternalAccountAccountDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Authority` param:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return err
	}
	// Serialize `ClientType` param:
	err = encoder.Encode(obj.ClientType)
	if err != nil {
		return err
	}
	// Serialize `SignerAddr` param:
	err = encoder.Encode(obj.SignerAddr)
	if err != nil {
		return err
	}
	// Serialize `PeptideChainId` param:
	err = encoder.Encode(obj.PeptideChainId)
	if err != nil {
		return err
	}
	return nil
}

func (obj *InternalAccountAccount) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(InternalAccountAccountDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[151 149 233 78 143 12 17 254]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return err
	}
	// Deserialize `ClientType`:
	err = decoder.Decode(&obj.ClientType)
	if err != nil {
		return err
	}
	// Deserialize `SignerAddr`:
	err = decoder.Decode(&obj.SignerAddr)
	if err != nil {
		return err
	}
	// Deserialize `PeptideChainId`:
	err = decoder.Decode(&obj.PeptideChainId)
	if err != nil {
		return err
	}
	return nil
}

type ProofCacheAccountAccount struct {
	Cache []byte
}

var ProofCacheAccountAccountDiscriminator = [8]byte{238, 17, 216, 242, 172, 224, 249, 126}

func (obj ProofCacheAccountAccount) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(ProofCacheAccountAccountDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Cache` param:
	err = encoder.Encode(obj.Cache)
	if err != nil {
		return err
	}
	return nil
}

func (obj *ProofCacheAccountAccount) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(ProofCacheAccountAccountDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[238 17 216 242 172 224 249 126]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Cache`:
	err = decoder.Decode(&obj.Cache)
	if err != nil {
		return err
	}
	return nil
}
