// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package polymer_prover

import ag_solanago "github.com/gagliardetto/solana-go"

var Addresses = map[string]ag_solanago.PublicKey{
	"11111111111111111111111111111111":             ag_solanago.MustPublicKeyFromBase58("11111111111111111111111111111111"),
	"CdvSq48QUukYuMczgZAVNZrwcHNshBdtqrjW26sQiGPs": ag_solanago.MustPublicKeyFromBase58("CdvSq48QUukYuMczgZAVNZrwcHNshBdtqrjW26sQiGPs"),
}
