// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package polymer_prover

import ag_solanago "github.com/gagliardetto/solana-go"

var Addresses = map[string]ag_solanago.PublicKey{
	"11111111111111111111111111111111":             ag_solanago.MustPublicKeyFromBase58("11111111111111111111111111111111"),
	"FtdxWoZXZKNYn1Dx9XXDE5hKXWf69tjFJUofNZuaWUH3": ag_solanago.MustPublicKeyFromBase58("FtdxWoZXZKNYn1Dx9XXDE5hKXWf69tjFJUofNZuaWUH3"),
}
