// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package polymer_prover

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// LoadProof is the `load_proof` instruction.
type LoadProof struct {
	ProofChunk *[]byte

	// [0] = [WRITE] cache_account
	//
	// [1] = [WRITE, SIGNER] authority
	//
	// [2] = [] system_program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewLoadProofInstructionBuilder creates a new `LoadProof` instruction builder.
func NewLoadProofInstructionBuilder() *LoadProof {
	nd := &LoadProof{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	nd.AccountMetaSlice[2] = ag_solanago.Meta(Addresses["11111111111111111111111111111111"])
	return nd
}

// SetProofChunk sets the "proof_chunk" parameter.
func (inst *LoadProof) SetProofChunk(proof_chunk []byte) *LoadProof {
	inst.ProofChunk = &proof_chunk
	return inst
}

// SetCacheAccount sets the "cache_account" account.
func (inst *LoadProof) SetCacheAccount(cacheAccount ag_solanago.PublicKey) *LoadProof {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(cacheAccount).WRITE()
	return inst
}

func (inst *LoadProof) findFindCacheAddress(authority ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// path: authority
	seeds = append(seeds, authority.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindCacheAddressWithBumpSeed calculates CacheAccount account address with given seeds and a known bump seed.
func (inst *LoadProof) FindCacheAddressWithBumpSeed(authority ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindCacheAddress(authority, bumpSeed)
	return
}

func (inst *LoadProof) MustFindCacheAddressWithBumpSeed(authority ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCacheAddress(authority, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindCacheAddress finds CacheAccount account address with given seeds.
func (inst *LoadProof) FindCacheAddress(authority ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindCacheAddress(authority, 0)
	return
}

func (inst *LoadProof) MustFindCacheAddress(authority ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCacheAddress(authority, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetCacheAccount gets the "cache_account" account.
func (inst *LoadProof) GetCacheAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *LoadProof) SetAuthorityAccount(authority ag_solanago.PublicKey) *LoadProof {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).WRITE().SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *LoadProof) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *LoadProof) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *LoadProof {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *LoadProof) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

func (inst LoadProof) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_LoadProof,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst LoadProof) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *LoadProof) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.ProofChunk == nil {
			return errors.New("ProofChunk parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.CacheAccount is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *LoadProof) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("LoadProof")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param(" ProofChunk", *inst.ProofChunk))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("        cache_", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("     authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("system_program", inst.AccountMetaSlice.Get(2)))
					})
				})
		})
}

func (obj LoadProof) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `ProofChunk` param:
	err = encoder.Encode(obj.ProofChunk)
	if err != nil {
		return err
	}
	return nil
}
func (obj *LoadProof) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `ProofChunk`:
	err = decoder.Decode(&obj.ProofChunk)
	if err != nil {
		return err
	}
	return nil
}

// NewLoadProofInstruction declares a new LoadProof instruction with the provided parameters and accounts.
func NewLoadProofInstruction(
	// Parameters:
	proof_chunk []byte,
	// Accounts:
	cacheAccount ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *LoadProof {
	return NewLoadProofInstructionBuilder().
		SetProofChunk(proof_chunk).
		SetCacheAccount(cacheAccount).
		SetAuthorityAccount(authority).
		SetSystemProgramAccount(systemProgram)
}
