// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package polymer_prover

import (
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
)

type InternalAccount struct {
	// store the owner's public key
	Authority ag_solanago.PublicKey

	// Client type used on peptide to generate the proof. It is part of the proof key
	ClientType string

	// Known signer address that signed the peptide state root
	SignerAddr     [20]uint8
	PeptideChainId uint64
}

func (obj InternalAccount) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Authority` param:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return err
	}
	// Serialize `ClientType` param:
	err = encoder.Encode(obj.ClientType)
	if err != nil {
		return err
	}
	// Serialize `SignerAddr` param:
	err = encoder.Encode(obj.SignerAddr)
	if err != nil {
		return err
	}
	// Serialize `PeptideChainId` param:
	err = encoder.Encode(obj.PeptideChainId)
	if err != nil {
		return err
	}
	return nil
}

func (obj *InternalAccount) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return err
	}
	// Deserialize `ClientType`:
	err = decoder.Decode(&obj.ClientType)
	if err != nil {
		return err
	}
	// Deserialize `SignerAddr`:
	err = decoder.Decode(&obj.SignerAddr)
	if err != nil {
		return err
	}
	// Deserialize `PeptideChainId`:
	err = decoder.Decode(&obj.PeptideChainId)
	if err != nil {
		return err
	}
	return nil
}

type ProofCacheAccount struct {
	Cache []byte
}

func (obj ProofCacheAccount) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Cache` param:
	err = encoder.Encode(obj.Cache)
	if err != nil {
		return err
	}
	return nil
}

func (obj *ProofCacheAccount) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Cache`:
	err = decoder.Decode(&obj.Cache)
	if err != nil {
		return err
	}
	return nil
}

type ValidationResultAccount struct {
	// whether the proof is valid or not
	IsValid bool

	// error message if the proof is not valid
	ErrorMessage string

	// the chain ID of the event that was validated
	ChainId uint32

	// the emitting contract address that emitted the event
	EmittingContract [20]uint8
	Topics           []byte

	// the unindexed data of the event that was validated
	UnindexedData []byte
}

func (obj ValidationResultAccount) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `IsValid` param:
	err = encoder.Encode(obj.IsValid)
	if err != nil {
		return err
	}
	// Serialize `ErrorMessage` param:
	err = encoder.Encode(obj.ErrorMessage)
	if err != nil {
		return err
	}
	// Serialize `ChainId` param:
	err = encoder.Encode(obj.ChainId)
	if err != nil {
		return err
	}
	// Serialize `EmittingContract` param:
	err = encoder.Encode(obj.EmittingContract)
	if err != nil {
		return err
	}
	// Serialize `Topics` param:
	err = encoder.Encode(obj.Topics)
	if err != nil {
		return err
	}
	// Serialize `UnindexedData` param:
	err = encoder.Encode(obj.UnindexedData)
	if err != nil {
		return err
	}
	return nil
}

func (obj *ValidationResultAccount) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `IsValid`:
	err = decoder.Decode(&obj.IsValid)
	if err != nil {
		return err
	}
	// Deserialize `ErrorMessage`:
	err = decoder.Decode(&obj.ErrorMessage)
	if err != nil {
		return err
	}
	// Deserialize `ChainId`:
	err = decoder.Decode(&obj.ChainId)
	if err != nil {
		return err
	}
	// Deserialize `EmittingContract`:
	err = decoder.Decode(&obj.EmittingContract)
	if err != nil {
		return err
	}
	// Deserialize `Topics`:
	err = decoder.Decode(&obj.Topics)
	if err != nil {
		return err
	}
	// Deserialize `UnindexedData`:
	err = decoder.Decode(&obj.UnindexedData)
	if err != nil {
		return err
	}
	return nil
}
