// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package polymer_prover

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ValidateEvent is the `validate_event` instruction.
type ValidateEventInstruction struct {

	// [0] = [WRITE, SIGNER] authority
	//
	// [1] = [WRITE] cache_account
	// ··········· LoadProof instruction
	//
	// [2] = [WRITE] result_account
	//
	// [3] = [] internal
	// ··········· which are unique to the program instance and required to validate the proof
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewValidateEventInstructionBuilder creates a new `ValidateEventInstruction` instruction builder.
func NewValidateEventInstructionBuilder() *ValidateEventInstruction {
	nd := &ValidateEventInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetAuthorityAccount sets the "authority" account.
func (inst *ValidateEventInstruction) SetAuthorityAccount(authority ag_solanago.PublicKey) *ValidateEventInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(authority).WRITE().SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *ValidateEventInstruction) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetCacheAccount sets the "cache_account" account.
// LoadProof instruction
func (inst *ValidateEventInstruction) SetCacheAccount(cacheAccount ag_solanago.PublicKey) *ValidateEventInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(cacheAccount).WRITE()
	return inst
}

func (inst *ValidateEventInstruction) findFindCacheAddress(authority ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: cache
	seeds = append(seeds, []byte{byte(0x63), byte(0x61), byte(0x63), byte(0x68), byte(0x65)})
	// path: authority
	seeds = append(seeds, authority.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindCacheAddressWithBumpSeed calculates CacheAccount account address with given seeds and a known bump seed.
func (inst *ValidateEventInstruction) FindCacheAddressWithBumpSeed(authority ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindCacheAddress(authority, bumpSeed)
	return
}

func (inst *ValidateEventInstruction) MustFindCacheAddressWithBumpSeed(authority ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCacheAddress(authority, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindCacheAddress finds CacheAccount account address with given seeds.
func (inst *ValidateEventInstruction) FindCacheAddress(authority ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindCacheAddress(authority, 0)
	return
}

func (inst *ValidateEventInstruction) MustFindCacheAddress(authority ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCacheAddress(authority, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetCacheAccount gets the "cache_account" account.
// LoadProof instruction
func (inst *ValidateEventInstruction) GetCacheAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetResultAccount sets the "result_account" account.
func (inst *ValidateEventInstruction) SetResultAccount(resultAccount ag_solanago.PublicKey) *ValidateEventInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(resultAccount).WRITE()
	return inst
}

func (inst *ValidateEventInstruction) findFindResultAddress(authority ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: result
	seeds = append(seeds, []byte{byte(0x72), byte(0x65), byte(0x73), byte(0x75), byte(0x6c), byte(0x74)})
	// path: authority
	seeds = append(seeds, authority.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindResultAddressWithBumpSeed calculates ResultAccount account address with given seeds and a known bump seed.
func (inst *ValidateEventInstruction) FindResultAddressWithBumpSeed(authority ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindResultAddress(authority, bumpSeed)
	return
}

func (inst *ValidateEventInstruction) MustFindResultAddressWithBumpSeed(authority ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindResultAddress(authority, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindResultAddress finds ResultAccount account address with given seeds.
func (inst *ValidateEventInstruction) FindResultAddress(authority ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindResultAddress(authority, 0)
	return
}

func (inst *ValidateEventInstruction) MustFindResultAddress(authority ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindResultAddress(authority, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetResultAccount gets the "result_account" account.
func (inst *ValidateEventInstruction) GetResultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetInternalAccount sets the "internal" account.
// which are unique to the program instance and required to validate the proof
func (inst *ValidateEventInstruction) SetInternalAccount(internal ag_solanago.PublicKey) *ValidateEventInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(internal)
	return inst
}

func (inst *ValidateEventInstruction) findFindInternalAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: internal
	seeds = append(seeds, []byte{byte(0x69), byte(0x6e), byte(0x74), byte(0x65), byte(0x72), byte(0x6e), byte(0x61), byte(0x6c)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindInternalAddressWithBumpSeed calculates Internal account address with given seeds and a known bump seed.
func (inst *ValidateEventInstruction) FindInternalAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindInternalAddress(bumpSeed)
	return
}

func (inst *ValidateEventInstruction) MustFindInternalAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindInternalAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindInternalAddress finds Internal account address with given seeds.
func (inst *ValidateEventInstruction) FindInternalAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindInternalAddress(0)
	return
}

func (inst *ValidateEventInstruction) MustFindInternalAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindInternalAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetInternalAccount gets the "internal" account.
// which are unique to the program instance and required to validate the proof
func (inst *ValidateEventInstruction) GetInternalAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst ValidateEventInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ValidateEvent,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ValidateEventInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ValidateEventInstruction) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.CacheAccount is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.ResultAccount is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Internal is not set")
		}
	}
	return nil
}

func (inst *ValidateEventInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ValidateEvent")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("authority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("   cache_", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("  result_", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta(" internal", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj ValidateEventInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *ValidateEventInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewValidateEventInstruction declares a new ValidateEvent instruction with the provided parameters and accounts.
func NewValidateEventInstruction(
	// Accounts:
	authority ag_solanago.PublicKey,
	cacheAccount ag_solanago.PublicKey,
	resultAccount ag_solanago.PublicKey,
	internal ag_solanago.PublicKey) *ValidateEventInstruction {
	return NewValidateEventInstructionBuilder().
		SetAuthorityAccount(authority).
		SetCacheAccount(cacheAccount).
		SetResultAccount(resultAccount).
		SetInternalAccount(internal)
}
