// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package polymer_prover

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ValidateEvent is the `validate_event` instruction.
type ValidateEvent struct {

	// [0] = [WRITE] cache_account
	//
	// [1] = [WRITE, SIGNER] authority
	//
	// [2] = [] internal
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewValidateEventInstructionBuilder creates a new `ValidateEvent` instruction builder.
func NewValidateEventInstructionBuilder() *ValidateEvent {
	nd := &ValidateEvent{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetCacheAccount sets the "cache_account" account.
func (inst *ValidateEvent) SetCacheAccount(cacheAccount ag_solanago.PublicKey) *ValidateEvent {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(cacheAccount).WRITE()
	return inst
}

func (inst *ValidateEvent) findFindCacheAddress(authority ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// path: authority
	seeds = append(seeds, authority.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindCacheAddressWithBumpSeed calculates CacheAccount account address with given seeds and a known bump seed.
func (inst *ValidateEvent) FindCacheAddressWithBumpSeed(authority ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindCacheAddress(authority, bumpSeed)
	return
}

func (inst *ValidateEvent) MustFindCacheAddressWithBumpSeed(authority ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCacheAddress(authority, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindCacheAddress finds CacheAccount account address with given seeds.
func (inst *ValidateEvent) FindCacheAddress(authority ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindCacheAddress(authority, 0)
	return
}

func (inst *ValidateEvent) MustFindCacheAddress(authority ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCacheAddress(authority, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetCacheAccount gets the "cache_account" account.
func (inst *ValidateEvent) GetCacheAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *ValidateEvent) SetAuthorityAccount(authority ag_solanago.PublicKey) *ValidateEvent {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).WRITE().SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *ValidateEvent) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetInternalAccount sets the "internal" account.
func (inst *ValidateEvent) SetInternalAccount(internal ag_solanago.PublicKey) *ValidateEvent {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(internal)
	return inst
}

func (inst *ValidateEvent) findFindInternalAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: internal
	seeds = append(seeds, []byte{byte(0x69), byte(0x6e), byte(0x74), byte(0x65), byte(0x72), byte(0x6e), byte(0x61), byte(0x6c)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindInternalAddressWithBumpSeed calculates Internal account address with given seeds and a known bump seed.
func (inst *ValidateEvent) FindInternalAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindInternalAddress(bumpSeed)
	return
}

func (inst *ValidateEvent) MustFindInternalAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindInternalAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindInternalAddress finds Internal account address with given seeds.
func (inst *ValidateEvent) FindInternalAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindInternalAddress(0)
	return
}

func (inst *ValidateEvent) MustFindInternalAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindInternalAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetInternalAccount gets the "internal" account.
func (inst *ValidateEvent) GetInternalAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

func (inst ValidateEvent) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ValidateEvent,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ValidateEvent) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ValidateEvent) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.CacheAccount is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Internal is not set")
		}
	}
	return nil
}

func (inst *ValidateEvent) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ValidateEvent")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("   cache_", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta(" internal", inst.AccountMetaSlice.Get(2)))
					})
				})
		})
}

func (obj ValidateEvent) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *ValidateEvent) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewValidateEventInstruction declares a new ValidateEvent instruction with the provided parameters and accounts.
func NewValidateEventInstruction(
	// Accounts:
	cacheAccount ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	internal ag_solanago.PublicKey) *ValidateEvent {
	return NewValidateEventInstructionBuilder().
		SetCacheAccount(cacheAccount).
		SetAuthorityAccount(authority).
		SetInternalAccount(internal)
}
