name: Solana Prover Contract

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test-solana-prover-contracts:
    runs-on: ubuntu-22.04-16core
    steps:
      - name: Build and test
        uses: ./.github/actions/build
