name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-test-release:
    runs-on: ubuntu-22.04-16core
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and test
        uses: ./.github/actions/build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          verifiable: 'yes'

      - name: Save compiled program
        if: success()
        run: |
          rm -rf release
          mkdir -p release
          sha256sum target/verifiable/polymer_prover.so > release/polymer_prover.sha256
          cp target/verifiable/polymer_prover.so release

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: release/**
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go/go.mod
          cache-dependency-path: go/go.sum
          cache: true

      - name: Check go registry
        run: |
          GOPROXY=proxy.golang.org go list -m github.com/polymerdao/solana-prover-contracts@${GITHUB_REF#refs/tags/}
